name: Check code

on:
  pull_request:

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm install -g bun && bun i
      - name: Check eslint
        run: |
          bun run lint