name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        run: |
          npm install -g bun && bun i
      - name: Config git
        run: |
          git config --global user.email "minh.luu@pionero.io"
          git config --global user.name "Minh Luu"
          git remote set-url origin git@github.com:minhluu-pionero/admin-ec-app-vue3.git
      - name: Build & deploy
        run: |
          bun run deploy